// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "openzeppelin-contracts-upgradeable/contracts/proxy/utils/Initializable.sol";
import "openzeppelin-contracts-upgradeable/contracts/access/AccessControlUpgradeable.sol";
import "openzeppelin-contracts-upgradeable/contracts/utils/PausableUpgradeable.sol";
import "./ICoreIdentityCredential.sol";

/**
 * @title IVerifier
 * @dev Interface for any autogenerated verifier contract
 */
interface IVerifier {
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[5] calldata _pubSignals 
    ) external view returns (bool);
}

interface IRevocationRegistry {
    function merkleRoot() external view returns (bytes32);
    function immediateRevocations(bytes32 nullifier) external view returns (bool);
}

contract ZKPVerification is Initializable, AccessControlUpgradeable, PausableUpgradeable {

    ICoreIdentityCredential public coreIdentityContract;
    IRevocationRegistry public revocationRegistry;

    /**
     * @dev Maps the credential type to its verifier. See ICoreIdentityCredential.CredentialType enum.
     */
    mapping(ICoreIdentityCredential.CredentialType => IVerifier) public verifiers;

    /**
     * @notice Specific roles for Service Providers.
     * @dev Instead of a global provider role, each credential type has its own dedicated role. 
     * This enforces the "scope" of a request: a provider can be authorized 
     * exclusively for AgeVerification without gaining access to Citizenship or Residency claims.
     */
    bytes32 public constant AGE_PROVIDER_ROLE = keccak256("AGE_PROVIDER_ROLE");
    bytes32 public constant CITIZENSHIP_PROVIDER_ROLE = keccak256("CITIZENSHIP_PROVIDER_ROLE");
    bytes32 public constant RESIDENCY_PROVIDER_ROLE = keccak256("RESIDENCY_PROVIDER_ROLE");

    /**
     * @notice Role able to set the ZKP verifier contracts.
     */
    bytes32 public constant ADMIN_ROLE = keccak256("ADMIN_ROLE");

    /**
     * @notice Emitted when a service provider successfully verifies a citizen's proof.
     * @param requester The address of the authorized service provider.
     * @param credentialId The ID of the credential being verified.
     * @param claimType The type of claim that was disclosed and verified.
     * @param timestamp The time the disclosure occurred.
     */
    event DisclosureRecorded(
        address indexed requester,
        bytes32 indexed credentialId,
        ICoreIdentityCredential.CredentialType indexed claimType,
        uint256 timestamp
    );

    /// @custom:oz-upgrades-unsafe-allow constructor
    constructor() {
        _disableInitializers();
    }

    function initialize(address _coreIdentityAddress, address _revocationRegistryAddress) public initializer {
        __AccessControl_init();
        __Pausable_init();

        _grantRole(DEFAULT_ADMIN_ROLE, msg.sender);
        _grantRole(ADMIN_ROLE, msg.sender);

        coreIdentityContract = ICoreIdentityCredential(_coreIdentityAddress);
        revocationRegistry = IRevocationRegistry(_revocationRegistryAddress); 
    }

    /**
     * @dev Allows admin to update the verifier contract address.
     * @param proofType Type of the proof, see ICoreIdentityCredential.CredentialType enum
     * @param verifierAddress Address of the new verifier contract.
     */
    function setVerifier(ICoreIdentityCredential.CredentialType proofType, address verifierAddress) external onlyRole(ADMIN_ROLE) {
        require(verifierAddress != address(0), "Invalid verifier address");
        verifiers[proofType] = IVerifier(verifierAddress);
    }

    /**
     * @dev Allows admin to update the RevocationRegistry contract address if upgraded.
     * @param _registryAddress Address of the new registry contract.
     */
    function setRevocationRegistry(address _registryAddress) external onlyRole(ADMIN_ROLE) {
        require(_registryAddress != address(0), "Invalid registry address");
        revocationRegistry = IRevocationRegistry(_registryAddress);
    }

    /**
     * @dev Checks that the credential exists (is active) and is not expired.
     * @param credentialId ID of the credential to check.
     */
    function _checkCredentialIsActive(bytes32 credentialId) internal view {
        ( , , , , uint64 expirationDate, , ICoreIdentityCredential.CredentialStatus status) = coreIdentityContract.credentials(credentialId);
        require(status == ICoreIdentityCredential.CredentialStatus.Active, "Credential is not active");
        require(expirationDate > block.timestamp, "Credential expired");
    }

    /**
     * @dev Checks that the credential exists (is active), is not expired, and is not revoked in the ZKP registry.
     * @param credentialId ID of the credential to check.
     * @param _pubSignals Public signals containing the Merkle root and nullifier.
     */
    function _checkCredentialIsActive(bytes32 credentialId, uint[5] calldata _pubSignals) internal view {
        // On-chain standard check (Core Identity)
        ( , , , , uint64 expirationDate, , ICoreIdentityCredential.CredentialStatus status) = coreIdentityContract.credentials(credentialId);
        require(status == ICoreIdentityCredential.CredentialStatus.Active, "Credential is not active");
        require(expirationDate > block.timestamp, "Credential expired");

        // Hybrid check (Revocation Registry)
        bytes32 proofRoot = bytes32(_pubSignals[3]);
        bytes32 nullifier = bytes32(_pubSignals[4]);

        require(!revocationRegistry.immediateRevocations(nullifier), "Credential immediately revoked");
        require(proofRoot == revocationRegistry.merkleRoot(), "Merkle root is not up-to-date");
    }

    /**
     * @dev Delegates the proof verification to the right auto generated verifier, depending on proofType.
     */
    function verifyZKProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[5] calldata _pubSignals,
        ICoreIdentityCredential.CredentialType _proofType
    ) internal view returns (bool) {
        IVerifier verifier = verifiers[_proofType];
        require(address(verifier) != address(0), "Unset verifier for this type");
        return verifier.verifyProof(_pA, _pB, _pC, _pubSignals);
    }

    /**
     * @notice Verifies selective disclosure proofs. If proof is valid, checks the validity of the credential.
     * @dev Also checks the validity of the public inputs, depending on the _claimType.
     */
    function verifySelectiveDisclosure(
        bytes32 _credentialId,
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[5] calldata _pubSignals,
        ICoreIdentityCredential.CredentialType _claimType
    ) internal view returns (bool) {
        // Fail Fast
        // Credential checked before proof data validation to save gas
        _checkCredentialIsActive(_credentialId, _pubSignals);
        
        bool isMathValid = verifyZKProof(_pA, _pB, _pC, _pubSignals, _claimType);
        require(isMathValid, "Invalid Proof");

        if (_claimType == ICoreIdentityCredential.CredentialType.AgeVerification) {
            // The ZKP must be bound to the citizen hash
            // This prevents user B from using user A's zkp to gain access (Replay attack)
            ( , bytes32 expectedCitizenHash, , , , , ) = coreIdentityContract.credentials(_credentialId);
            uint256 hashFromProof = (uint256(_pubSignals[0]) << 128) | uint256(_pubSignals[1]);
            require(uint256(expectedCitizenHash) == hashFromProof, "Proof not bound to this credential");

            // _pubSignals[2] is currentTimestamp. It is checked to prevent user from using future dates to appear over 18.
            // 5 minutes (300s) of tollerance (network or block validation delays).
            require(
                _pubSignals[2] <= block.timestamp + 300 && _pubSignals[2] >= block.timestamp - 300, 
                "Proof's currentTimestamp is not actual current time"
            );
        } else if (_claimType == ICoreIdentityCredential.CredentialType.Citizenship) {
            // Not Implemented
        } else if (_claimType == ICoreIdentityCredential.CredentialType.Residency) {
            // Not Implemented
        }

        // If everything went fine and nothing reverted
        return true; 
    }

    /**
     * @notice Verifies if a disclosure request is legitimate based on the requester's scope.
     * @dev Does not cause reverts, so it can be used on the front-end.
     * @param _requester The address attempting to request the disclosure.
     * @param _claimType The type of claim being requested.
     * @return bool True if the requester is authorized for this specific scope.
     */
    function validateDisclosureRequest(address _requester, ICoreIdentityCredential.CredentialType _claimType) public view returns (bool) {
        if (_claimType == ICoreIdentityCredential.CredentialType.AgeVerification) {
            return hasRole(AGE_PROVIDER_ROLE, _requester);
        } else if (_claimType == ICoreIdentityCredential.CredentialType.Citizenship) {
            return hasRole(CITIZENSHIP_PROVIDER_ROLE, _requester);
        } else if (_claimType == ICoreIdentityCredential.CredentialType.Residency) {
            return hasRole(RESIDENCY_PROVIDER_ROLE, _requester);
        }
        return false;
    }

    /**
     * @notice Creates an audit trail of the disclosure event.
     * @param _requester The authorized service provider who accessed the proof.
     * @param _credentialId The ID of the credential used.
     * @param _claimType The type of claim verified.
     */
    function recordDisclosureEvent(address _requester, bytes32 _credentialId, ICoreIdentityCredential.CredentialType _claimType) internal {
        emit DisclosureRecorded(_requester, _credentialId, _claimType, block.timestamp);
    }

    /**
     * @notice Main entry point for Service Providers to request and verify a specific claim.
     * @param _credentialId The ID of the citizen's credential.
     * @param _pA ZK Proof parameter A.
     * @param _pB ZK Proof parameter B.
     * @param _pC ZK Proof parameter C.
     * @param _pubSignals Public signals from the ZK Proof.
     * @param _claimType The specific claim being requested (e.g., AgeVerification).
     * @return bool True if the disclosure is valid and recorded.
     */
    function requestDisclosure(
        bytes32 _credentialId,
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[5] calldata _pubSignals,
        ICoreIdentityCredential.CredentialType _claimType
    ) external whenNotPaused returns (bool) {
        require(validateDisclosureRequest(msg.sender, _claimType), "Invalid disclosure request");
        bool isValid = verifySelectiveDisclosure(_credentialId, _pA, _pB, _pC, _pubSignals, _claimType);
        require(isValid, "Zero-Knowledge Proof validation failed");
        recordDisclosureEvent(msg.sender, _credentialId, _claimType);

        return true;
    }

    /**
     * @notice Puts the ZKP verification system in a paused state.
     */
    function pause() external onlyRole(ADMIN_ROLE) {
        _pause();
    }

    /**
     * @notice Unpauses the ZKP verification system.
     */
    function unpause() external onlyRole(ADMIN_ROLE) {
        _unpause();
    }
}